apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    creationTimestamp: null
    labels:
      app: zomatonode
      hasuraService: custom
    name: zomatonode
    namespace: '{{ cluster.metadata.namespaces.user }}'
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: zomatonode
      spec:
        containers:
        - image: hasura/base-git-image:0.7
          imagePullPolicy: IfNotPresent
          name: zomatonode
          env:
            - name: CLINET_SECRET
              valueFrom:
                secretKeyRef:
                  name: hasura-secrets
                  key: auth.facebook.client_secret
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: hasura-secrets
                  key: my.facebook.client_id
            - name: GOOGLE_KEY
              valueFrom:
                secretKeyRef:
                  name: hasura-secrets
                  key: auth.google.key
            - name: ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: hasura-secrets
                  key: admin.token
          ports:
          - containerPort: 8000
            protocol: TCP
          resources: {}
        securityContext: {}
        terminationGracePeriodSeconds: 0
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: null
    labels:
      app: zomatonode
      hasuraService: custom
    name: zomatonode
    namespace: '{{ cluster.metadata.namespaces.user }}'
  spec:
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
    selector:
      app: zomatonode
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata: {}
